version: '3'

services:
  passwordgen:
    build:
      context: .
      dockerfile: Dockerfile
    image: passwordgen
    container_name: passwordgen
    #ports:
    # - 7005:7005
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:stable-perl
    container_name: webserver
    restart: unless-stopped
    ports:
      - "7006:7006"
    volumes:
      - web-root:/var/www/html
      - ./Server/Nginx-Conf:/etc/nginx/conf.d
    depends_on:
      - passwordgen
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /
      o: bind